#!/usr/bin/env bash
#
# Copyright (C) 2016 Xenith Consulting Limited
# Author: Salim Badakhchani <salimb@xenithconsulting.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Switch on Debugging
#set -x

# Check user privileges
[[ $(id -u) == 0 ]] || echo -e "\n# This script requires root privileges to run"

# Define logfile
LOG="/root/install.log"

echo -e "########################################################################" > $LOG
echo -e "Installing System..." >> $LOG
echo -e "########################################################################\n" >> $LOG
echo -e $(date) >> $LOG
echo >> $LOG

# Execution statements logicaly grouped into functions.

disable_firewall () {
    echo -e "# Disabling..." >> $LOG
    systemctl stop iptables > /dev/null 2>&1 
    systemctl stop ip6tables > /dev/null 2>&1
    systemctl stop firewalld > /dev/null 2>&1
}

update_system () {
    echo -e "# Updating system..." >> $LOG
    yum -y update > /dev/null 2>&1
}

install_packages () {
    echo -e "# Installing packages..." >> $LOG
    [[ -f "/etc/yum.repos.d/rpmforge.repo" ]] || rpm -Uvh ftp://139.162.181.50/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
    yum -y install docker git wget unzip net-tools bind bind-utils patch mlocate maven htop iftop curl tree
}

setup_env () {
    echo "# Creating profile..." >> $LOG
    cat > /etc/profile.d/custom.sh << 'EOF'
# Prompt colors
if [ `whoami` != "root" ]; then
    PS1='\[\e[32m\][\u@\h \W]\$\[\e[0m\] '
else
    PS1='\[\e[31m\][\u@\h \W]\$\[\e[0m\] '
fi

# Aliases
alias c='clear'
alias h='history'
alias m='less /var/log/messages'
alias l='ll -has '
alias n='netstat -vatulpn | grep'
alias p='ps -A | grep'
alias g='gvim'

# Configure bash history 
HISTSIZE='1000000'
HISTIGNORE=' *:&:?:??'
HISTCONTROL='ignoreboth:erasedups'

export HISTSIZE HISTIGNORE HISTCONTROL

# Turn on bash history options
shopt -s histappend histreedit histverify

# Sync term history
history() {
  history_sync
  builtin history "$@"
}

history_sync() {
  builtin history -a         
  HISTFILESIZE=$HISTSIZE     
  builtin history -c         
  builtin history -r         
}

PROMPT_COMMAND=history_sync
EOF

    cat > /etc/profile.d/openshift.sh << 'EOF'
export OPENSHIFT=/opt/openshift-origin-v1.2
export OPENSHIFT_VERSION=v1.2.0-rc1
export PATH=$OPENSHIFT:$PATH
export KUBECONFIG=$OPENSHIFT/openshift.local.config/master/admin.kubeconfig
export CURL_CA_BUNDLE=$OPENSHIFT/openshift.local.config/master/ca.crt
EOF

}
source /etc/profile.d/custom.sh
source /etc/profile.d/openshift.sh

install_docker () {
    echo -e "# Patching docker" >> $LOG
    [[ -f "/etc/sysconfig/docker.orig" ]]; mv /etc/sysconfig/docker.orig /etc/sysconfig/docker
    cp -p /etc/sysconfig/docker /etc/sysconfig/docker.orig
    cat > /tmp/docker.patch << 'EOF'
--- /etc/sysconfig/docker	2015-12-10 17:57:32.000000000 -0500
+++ /etc/sysconfig/docker	2016-03-31 02:28:46.835000000 -0400
@@ -21,6 +21,7 @@
 # distributed, you can tell docker to not look for full authorization by
 # adding the registry to the INSECURE_REGISTRY line and uncommenting it.
 # INSECURE_REGISTRY='--insecure-registry'
+INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'
 
 # On an SELinux system, if you remove the --selinux-enabled option, you
 # also need to turn on the docker_transition_unconfined boolean.
EOF
(cd / && patch -p0) < /tmp/docker.patch
rm -f /tmp/docker.patch

echo -e "# Initialising docker" >> $LOG
systemctl enable docker
systemctl restart docker

docker pull openshift/origin-pod:$OPENSHIFT_VERSION
docker pull openshift/origin-sti-builder:$OPENSHIFT_VERSION
docker pull openshift/origin-docker-builder:$OPENSHIFT_VERSION
docker pull openshift/origin-deployer:$OPENSHIFT_VERSION
docker pull openshift/origin-docker-registry:$OPENSHIFT_VERSION
docker pull openshift/origin-haproxy-router:$OPENSHIFT_VERSION
}

install_nameserver () {
    echo -e "# Patching bind" >> $LOG
    [[ -f "/etc/named.conf.orig" ]]; mv /etc/named.conf.orig /etc/named.conf
    cp -p /etc/named.conf /etc/named.conf.orig
    cat > /tmp/bind.patch << 'EOF'
--- /etc/named.conf	2015-06-01 06:43:48.000000000 -0400
+++ /etc/named.conf	2016-04-18 10:15:51.743000000 -0400
@@ -8,13 +8,14 @@
 //
 
 options {
-	listen-on port 53 { 127.0.0.1; };
+	listen-on port 53 { 127.0.0.1; 192.168.122.101; };
 	listen-on-v6 port 53 { ::1; };
 	directory 	"/var/named";
 	dump-file 	"/var/named/data/cache_dump.db";
 	statistics-file "/var/named/data/named_stats.txt";
 	memstatistics-file "/var/named/data/named_mem_stats.txt";
-	allow-query     { localhost; };
+	allow-query     { any; };
+	forwarders	{ 8.8.8.8; 8.8.4.4; };
 
 	/* 
 	 - If you are building an AUTHORITATIVE DNS server, do NOT enable recursion.
@@ -30,6 +31,7 @@
 
 	dnssec-enable yes;
 	dnssec-validation yes;
+	dnssec-lookaside auto;
 
 	/* Path to ISC DLV key */
 	bindkeys-file "/etc/named.iscdlv.key";
@@ -52,6 +54,18 @@
 	file "named.ca";
 };
 
+zone "example.com" IN {
+	type master;
+	file "example.com.zone";
+	allow-update { none; };
+};
+        
+zone "122.168.192.in-addr.arpa" IN {
+	type master;
+	file "122.168.192.zone";
+	allow-update { none; };
+};
+
 include "/etc/named.rfc1912.zones";
 include "/etc/named.root.key";
EOF
    (cd / && patch -p0) < /tmp/bind.patch
    rm -f /tmp/bind.patch
  
    echo -e "# Creating reverse zone file" >> $LOG
    cat > /var/named/122.168.192.zone << 'EOF'
$ORIGIN 122.168.192.in-addr.arpa.
$TTL 86400
@       IN      SOA     kojak.example.com.      hostmaster.example.com. (
                        2016032801 ; serial
                        21600      ; refresh after 6 hours
                        3600       ; retry after 1 hour
                        604800     ; expire after 1 week
                        86400 )    ; minimum TTL of 1 day
;
@       IN     NS      kojak.example.com.
;
52     IN      PTR     kojak.example.com.
EOF
     
    echo -e "# Creating zone file" >> $LOG
    cat > /var/named/example.com.zone << 'EOF'
$ORIGIN example.com.
$TTL 86400
@               IN      SOA     kojak.example.com.      hostmaster.example.com. (
                        2016041801 ; serial
                        21600      ; refresh after 6 hours
                        3600       ; retry after 1 hour
                        604800     ; expire after 1 week
                        86400 )    ; minimum TTL of 1 day
;
;

                IN      NS      kojak.example.com.
kojak           IN      A       192.168.122.101

*.example.com.  300 IN  A       192.168.122.101
EOF
    chown -R root:named /var/named
    systemctl enable named && systemctl start named

    echo -e "# Creating resolve file" >> $LOG
    cat > /etc/resolv.conf << 'EOF'
# Generated by Kojak
domain example.com
search example.com
nameserver 127.0.0.1
EOF
}

install_openshift () {
    echo -e "# Installing openshift" >> $LOG
    mkdir /opt/openshift-origin-v1.2
    [[ -f "/tmp/openshift-origin-server-v1.2.0-rc1-061e6d4-linux-64bit.tar.gz" ]] || \
    wget https://github.com/openshift/origin/releases/download/v1.2.0-rc1/openshift-origin-server-v1.2.0-rc1-061e6d4-linux-64bit.tar.gz -P /tmp
    tar -zxvf /tmp/openshift-origin-server-v1.2.0-rc1-061e6d4-linux-64bit.tar.gz -C /opt/openshift-origin-v1.2/ --strip-components 1

    cat > /etc/systemd/system/openshift-origin.service << 'EOF'
[Unit]
Description=Origin Master Service
After=docker.service
Requires=docker.service
 
[Service]
Restart=always
RestartSec=10s
ExecStart=/opt/openshift-origin-v1.2/openshift start
WorkingDirectory=/opt/openshift-origin-v1.2
 
[Install]
WantedBy=multi-user.target
EOF

    cd $OPENSHIFT
    $OPENSHIFT/openshift start --write-config=openshift.local.config 
    sed -i 's/router.default.svc.cluster.local/example.com/' \
    $OPENSHIFT/openshift.local.config/master/master-config.yaml
    chmod +r $OPENSHIFT/openshift.local.config/master/admin.kubeconfig
    chmod +r $OPENSHIFT/openshift.local.config/master/openshift-registry.kubeconfig
    chmod +r $OPENSHIFT/openshift.local.config/master/openshift-router.kubeconfig

    systemctl daemon-reload
    systemctl enable openshift-origin
    systemctl start openshift-origin

    echo -e "# Configuring openshift" >> $LOG
    source /etc/profile.d/openshift.sh

    while ! timeout 1 bash -c "echo > /dev/tcp/localhost/8443"; do echo -e "# Retrying...please be patient" && sleep 12 ; done
    echo -e "# Creating service accounts for registry and router" >> $LOG
    oc login -u system:admin -n default
    oc project default
    echo '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"registry"}}' | oc create -f -
    echo '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"router"}}' | oc create -f -
    [[ -f "/tmp/jq-linux64" ]] || wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -P /tmp
    chmod +x /tmp/jq-linux64
    oc get scc privileged -o json | /tmp/jq-linux64 '.users |= .+ ["system:serviceaccount:default:registry"]' | oc replace scc -f -
    oc get scc privileged -o json | /tmp/jq-linux64 '.users |= .+ ["system:serviceaccount:default:router"]' | oc replace scc -f -
	
    echo -e "# Creating user roles" >> $LOG
    oadm policy add-cluster-role-to-user cluster-admin admin
	
    echo -e "# Creating docker registry" >> $LOG
    mkdir /opt/openshift-registry
    chcon -Rt svirt_sandbox_file_t /opt/openshift-registry
    chown root:root /opt/openshift-registry
    oadm policy add-scc-to-user privileged -z registry 
    oadm registry --service-account=registry --mount-host=/opt/openshift-registry
	
    echo -e "# Creating router" >> $LOG
    oadm policy add-scc-to-user hostnetwork -z router
    oadm router router --replicas=1 --service-account=router 
    
    
    [[ -f "/tmp/openshift-ansible.git" ]] || cd /tmp && git clone https://github.com/openshift/openshift-ansible.git
    cd /tmp/openshift-ansible/roles/openshift_examples/files/examples/latest/
    for image in image-streams/image-streams-centos7.json; do cat $image | oc create -n openshift -f -; done
    for image in db-templates/*.json; do cat $image | oc create -n openshift -f -; done
    for image in quickstart-templates/*.json; do cat $image | oc create -n openshift -f -; done

}

install_fabric8 () {

    echo -e "# Downloading gofabric8" >> $LOG
    cd /opt
    mkdir gofabric8
    [[ -f "/tmp/gofabric8-0.4.9-linux-amd64.tar.gz" ]] || \
    wget https://github.com/fabric8io/gofabric8/releases/download/v0.4.9/gofabric8-0.4.9-linux-amd64.tar.gz -P /tmp
    tar zxfv /tmp/gofabric8-0.4.9-linux-amd64.tar.gz -C /opt/gofabric8/

    echo -e "# Installing fabric8" >> $LOG
    /opt/gofabric8/gofabric8 deploy --yes --namespace="default" --domain example.com  
    /opt/gofabric8/gofabric8 secrets --yes
    oc get oauthclient fabric8

    echo -e "# Configure cd-pipeline" >> $LOG
    /opt/gofabric8/gofabric8 pull cd-pipeline 

    echo -e "# Validate installaiton" >> $LOG
    /opt/gofabric8/gofabric8 validate --namespace="default"
}

install_apps () {

    oc process -v DOMAIN=$KUBERNETES_DOMAIN -f \
    http://repo1.maven.org/maven2/io/fabric8/devops/packages/management/2.2.101/management-2.2.101-kubernetes.json \
    | oc create -f -

    oc process -v DOMAIN=$KUBERNETES_DOMAIN -f \
    http://repo1.maven.org/maven2/io/fabric8/devops/packages/logging/2.2.101/logging-2.2.101-kubernetes.json \
    | oc create -f -

    oc process -v DOMAIN=$KUBERNETES_DOMAIN -f \
    http://repo1.maven.org/maven2/io/fabric8/devops/packages/metrics/2.2.101/metrics-2.2.101-kubernetes.json \
    | oc create -f -
}

disable_firewall
update_system
install_packages
setup_env
install_docker
install_nameserver
install_openshift
install_fabric8
#install_apps

