#!/usr/bin/env bash
#
# Copyright (C) 2016 Xenith Consulting Limited
# Author: Salim Badakhchani <salimb@xenithconsulting.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Switch on Debugging
set -x

# Check user privileges
[[ $(id -u) == 0 ]] || echo -e "\n# This script requires root privileges to run"

# Define logfile
LOG="/root/fabric8.log"

echo -e "########################################################################" > $LOG
echo -e "Installing System..." >> $LOG
echo -e "########################################################################\n" >> $LOG
echo -e $(date) >> $LOG
echo >> $LOG

install_fabric8 () {

    echo -e "# Downloading gofabric8" >> $LOG
    cd /opt
    mkdir gofabric8
    [[ -f "/tmp/gofabric8-0.4.9-linux-amd64.tar.gz" ]] || \
    wget https://github.com/fabric8io/gofabric8/releases/download/v0.4.9/gofabric8-0.4.9-linux-amd64.tar.gz -P /tmp
    tar zxfv /tmp/gofabric8-0.4.9-linux-amd64.tar.gz -C /opt/gofabric8/

    echo -e "# Installing fabric8" >> $LOG
    /opt/gofabric8/gofabric8 deploy --yes --namespace="default" --domain apps.example.com
    /opt/gofabric8/gofabric8 secrets --yes
    oc get oauthclient fabric8

    echo -e "# Configure cd-pipeline" >> $LOG
    /opt/gofabric8/gofabric8 pull cd-pipeline

    echo -e "# Validate installaiton" >> $LOG
    /opt/gofabric8/gofabric8 validate --namespace="default"
}

install fabric8
