#!/usr/bin/env bash
#
# Copyright (C) 2016 Xenith Consulting Limited
# Author: Salim Badakhchani <salimb@xenithconsulting.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Switch on Debugging
set -x

# Check user privileges
[[ $(id -u) == 0 ]] || echo -e "\n# This script requires root privileges to run"

# Define logfile
LOG="/root/install.log"

# Execution statements logically grouped into functions.

install_docker() {
    echo -e "# Installing docker..." >> ${LOG}
    cat > /etc/yum.repos.d/docker.repo <<-'EOF'
[docker-engine]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/$releasever/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
EOF

    yum -y install docker-engine
}

patch_docker() {
    echo -e "# Patching docker..." >> ${LOG} 
    [[ -f "/usr/lib/systemd/system/docker.service.orig" ]]; mv \
    /usr/lib/systemd/system/docker.service.orig /usr/lib/systemd/system/docker.service
    cp -p /usr/lib/systemd/system/docker.service /usr/lib/systemd/system/docker.service.orig
    cat > /tmp/docker.patch << 'EOF'
--- /usr/lib/systemd/system/docker.service    2016-07-27 19:35:00.000000000 -0400
+++ /usr/lib/systemd/system/docker.service    2016-07-30 18:53:27.739000000 -0400
@@ -8,7 +8,7 @@
 # the default is not to use systemd for cgroups because the delegate issues still
 # exists and systemd currently does not support the cgroup feature set required
 # for containers run by docker
-ExecStart=/usr/bin/dockerd
+ExecStart=/usr/bin/dockerd --insecure-registry=172.0.0.0/8
 ExecReload=/bin/kill -s HUP $MAINPID
 # Having non-zero Limit*s causes performance problems due to accounting overhead
 # in the kernel. We recommend using cgroups to do container-local accounting.
EOF
    (cd / && patch -p0) < /tmp/docker.patch
    rm -f /tmp/docker.patch
}
    
initialise_docker() { 
    echo -e "# Initialising docker..." >> ${LOG}
    usermod -aG docker $(whoami)
    systemctl daemon-reload
    systemctl enable docker
    systemctl restart docker
}

install_docker
patch_docker
initialise_docker
