#!/usr/bin/env bash
#
# Copyright (C) 2016 Xenith Consulting Limited
# Author: Salim Badakhchani <salimb@xenithconsulting.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Set deugging
#set -x 

read -d '' USAGE <<- EOF
Usage: diff-files [options] <directory> <directory>
-h, --help            show this help message and exit
-d, --cert            prompt user for directory names
EOF


if [[ $# < 2 ]] || [[ $# > 4 ]]; then echo "${USAGE}"; fi
while [[ $# > 1 ]]; do OPTS="$1"; shift

case $OPTS in
    -d|--diff)
    echo "Checking for differences between files in  ${1} and ${2}"
            diff -ru $1 $2
    shift
    ;;
    -h|--help)
    echo "Help options include"
    shift
    ;;
    *)
    echo "${USAGE}" # unknown option
    ;;
    \?)
    echo "${USAGE} option" # unknown option
    ;;
esac
done
